### ISSUE TITLE
被写体とスポットを結びつけるロジックを作る

### ISSUE THREAD

**Issue by mido1003** [shakugo/KameraYohou#32]

**Comment by tonchan1216** [comment]
# Todo
ユーザーが撮りたい被写体情報（subject）を条件に、
おすすめスポットから検索してくる

**Comment by tonchan1216** [comment]
FilterExpressionのcontainsが使えそう
contains() OR contains() ......

https://stackoverflow.com/questions/43793888/how-to-make-search-using-contains-with-dynamodb

**Comment by tonchan1216** [comment]
containsで行けた
https://github.com/shakugo/KameraLambda/pull/14
