### ISSUE TITLE
おすすめスポットの一覧の表示

### ISSUE THREAD

**Issue by mido1003** [shakugo/KameraYohou#7]
- [x]  トップページを作る
- [x] リストビュー的な何かを作る
- [x] 配列を繰り返し処理する
- [x] APIからデータを引っ張る
- [ ] DBから情報取得し、表示する
- [ ] コンソール上での手動入力も含む

**Comment by tonchan1216** [comment]
Lambda関数いらない説

**Comment by tonchan1216** [comment]
一旦Mockサーバとつなげてできまあした。
